name: Deploy to App Engine

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    permissions:
       contents: 'read'
       id-token: 'write'
  
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: lively-goal-428803-t6
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/984592306304/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        project_id: lively-goal-428803-t6

    - name: Initialize App Engine (if not exists)
      run: |
        if ! gcloud app describe --project=${{ secrets.GCP_PROJECT_ID }}; then
            gcloud app create --region=asia-southeast2
        fi

    - name: Deploy to Google App Engine
      uses: google-github-actions/deploy-appengine@v2
